name: widgetbook_test_demo
description: Hypothetical demo for how widgetbook_test package will look like.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.2.0
  widgetbook_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  widgetbook_generator: ^3.1.0
  build_runner: ^2.0.0

  # Using this fork as alchemist is not currently
  # compatible with Flutter 3.13
  alchemist:
    git:
      url: https://github.com/ABausG/alchemist/
      ref: flutter-3-13

flutter:
  uses-material-design: true
